version: '3.1'

services:

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=flights
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


  flights-service:
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - PORT=8086
      - DATABASE_URL=mysql://root:secret@database:3306/flights
    build: ./flights-app
    ports:
      - 8086:8086
    #To keep the terminal open after running
    stdin_open: true
    tty: true

volumes:
  db:
  