version: '3.1'

services:


  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=auth
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


  auth-service:
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - AUTH_PORT=8085
      - AUTH_SALT=$2a$04$2YFv3bhTr6JuNRxziRkw8e
      - AUTH_SECRET_TOKEN=b05248bdc8082daf41d3c3c03595a3d528a4348e7b29938bbb24b6d0f241d3008e55f85a0ac92e75164d040cd948210aaa528a3fa81de1a7e3b2d7a3887ec3bd
      - DATABASE_URL=mysql://root:secret@database:3306/auth
    build: ./auth-app
    ports:
      - 8085:8085
    #To keep the terminal open after running
    stdin_open: true
    tty: true

volumes:
  db:
  